install.packages("googlesheets4")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("tidyr")
install.packages("reshape2")
install.packages("janitor")
install.packages("gridExtra")

library(googlesheets4)
library(dplyr)
library(MASS)
library(tidyr)
library(janitor)
#gs4_auth()
library(reshape2)
library(gridExtra)
