install.packages("googlesheets4")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("tidyr")
install.packages("reshape2")
install.packages("janitor")
install.packages("gridExtra")
install.packages("caret")
install.packages(c("tidyverse", "tidytext", "textdata"))
install.packages("syuzhet")
install.packages("ggtext")


library(ggplot2)
library(googlesheets4)
library(dplyr)
library(MASS)
library(tidyr)
library(janitor)
library(reshape2)
library(gridExtra)
library(caret)
library(cluster)
library(lattice)
library(tidyverse)
library(tidytext)
library(textdata)
library(syuzhet)
library(stringr)
library(wordcloud)
library(RColorBrewer)
library(ggtext)

gs4_auth()
