install.packages("googlesheets4")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("tidyr")
install.packages("reshape2")
install.packages("janitor")
install.packages("gridExtra")
install.packages("caret")

library(googlesheets4)
library(dplyr)
library(MASS)
library(tidyr)
library(janitor)
library(reshape2)
library(gridExtra)
library(caret)
library(cluster)
library(lattice)
library(tidytext)
library(textdata) # For sentiment lexicons

gs4_auth()
